config/routes.rb
Rails.application.routes.draw do
  resources :collaborations
  get 'charges/create'

  devise_for :users

  resources :users, only: [:show, :index]
  get 'controller/downgrade' => 'users#downgrade', as: :downgrade_user


  resources :wikis do
    resources :collaborations, only: [:index, :create, :destroy]
  end

  resources :charges, only: [:new, :create]

  root 'welcome#index'

  get 'welcome/index'

  get 'welcome/about'
end

app/models/Amount.rb
# REVIEW is this the best way to do this? Is it in the right directory?
# Does this even need to be a class?
class Amount
  attr_accessor :default

  def initialize
    @default = 10_00
  end
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :collaborations
  has_many :wikis

  enum role: [:member, :premium, :admin]

  after_initialize :set_default_role

  def set_default_role
    self.role ||= 'member'
  end

  def downgrade_role
    self.member!
    wikis.update_all(private: false)
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations

  validates :title, presence: true
  validates :body, presence: true

  def collaboration_for(user)
    collaborations.find_by(user: user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
require 'amount'

class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd' )

    flash[:notice] = "Thank you for your purchase, #{current_user.email}."

    current_user.premium!

    flash[:notice] = "#{current_user.email} account upgraded to #{current_user.role}."
    redirect_to current_user

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

  end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_collaboration, only: [:destroy]
  before_action :set_wiki

  def index
    @users = User.all
  end

  def new
    @collaboration = Collaboration.new
  end

  def create
    @collaboration = @wiki.collaborations.new(user_id: params[:user_id])

    respond_to do |format|
      if @collaboration.save
        format.html { redirect_to wiki_collaborations_path(@wiki), notice: 'Collaboration was successfully created.' }
        format.json { render :show, status: :created, location: @collaboration }
      else
        format.html { redirect_to wiki_collaborations_path(@wiki) }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collaboration.destroy
    respond_to do |format|
      format.html { redirect_to wiki_collaborations_path(@wiki), notice: 'Collaboration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_collaboration
      @collaboration = Collaboration.find(params[:id])
    end

    def set_wiki
      @wiki = current_user.wikis.find(params[:wiki_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def downgrade
    current_user.downgrade_role

    flash[:notice] = "#{current_user.email} account downgraded to #{current_user.role}."
    redirect_to user_path(current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        wiki_log = @wiki.title.truncate(30)
        format.html { redirect_to @wiki, notice: "Wiki \" #{wiki_log}\" was successfully created."  }
        format.json { render :show, status: :created, location: @wiki}
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @wiki

    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki}
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @wiki
    @wiki.destroy
    respond_to do |format|
      wiki_log = @wiki.title.truncate(30)
      format.html { redirect_to wikis_url, notice: "Wiki \" #{wiki_log}\" was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click below to confirm purchase</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborations/_form.html.erb
<%= form_for(@collaboration) do |f| %>
  <% if @collaboration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collaboration.errors.count, "error") %> prohibited this collaboration from being saved:</h2>

      <ul>
      <% @collaboration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collaborations/edit.html.erb
<h1>Editing Collaboration</h1>

<%= render 'form' %>

<%= link_to 'Show', @collaboration %> |
<%= link_to 'Back', collaborations_path %>

app/views/collaborations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Collaborations</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <% if @wiki.users.include?(user) %>
            <% collaboration =  @wiki.collaboration_for(user) %>
            <%= link_to 'Remove as Collaborator', [@wiki, collaboration], method: :delete, class: "btn btn-danger" %>
          <% else %>
            <%= link_to "Add as Collaborator", wiki_collaborations_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collaboration', new_collaboration_path %>

app/views/collaborations/new.html.erb
<h1>New Collaboration</h1>

<%= render 'form' %>

<%= link_to 'Back', collaborations_path %>

app/views/collaborations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_collaboration_path(@collaboration) %> |
<%= link_to 'Back', collaborations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikease</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-pills">
        <li role="presentation"  class="blue-pill"> <%= link_to "Home", welcome_index_path %> </li>
        <li role="presentation"  class="blue-pill"> <%= link_to "About", welcome_about_path %> </li>
        <li role="presentation"  class="blue-pill"> <%= link_to "Users", users_path %> </li>
        <li role="presentation"  class="blue-pill"> <%= link_to "Wikis", wikis_path %> </li>
        <li role="presentation"  class="pull-right new-wiki-button" id="new_wiki_button"> <%= link_to 'Create New Wiki', new_wiki_path %> </li>
      </ul>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          <strong><%= link_to current_user.email, user_path(current_user) %></strong>
          </br>
          <%= link_to 'Settings', edit_user_registration_path, class: "navbar-link" %>
           - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "navbar-link" %>
           - <%= link_to "Sign In", new_user_session_path, class: 'navbar-link' %>
        <% end %>
      </div>
      <div class="clearfix bump-down"></div>


      <div class="flash">
      <% if flash[:notice] %>
        <div class= "alert alert-succes">
          <button type="button" class=close data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class= "alert alert-danger"
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class= "alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      </div>

    <%= yield %>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr class="index-table-header-container">
      <td class="index-table-header" id="table-header"> Users </td>
      <td class="index-table-header" id="table-header"> Joined </td>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user_path(user) %></td>
        <td> <%= user.created_at.strftime("%B %d, %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="row">
  <h2 class="user-show-heading"><%= @user.email %></h2>
  <div class="user-show-heading btn-xs btn-primary" id="role-button"><%= @user.role %> user</div>
  <h3> You have <%= @user.wikis.count %> Entries</h3>
</div>

<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.wikis.each do |wiki| %>
    <tr>
      <td>
        <div class="option-buttons"> <%= link_to wiki.title.truncate(60), wiki_path(wiki) %> </div>

        <div class="option-buttons pull-right">
          <% if wiki.user == current_user || current_user.role == 'admin' %>
            <div id="user-show-tiny-buttons">
              <%= link_to 'Edit', edit_wiki_path(wiki), class: "btn-sm btn-info" %> <%= link_to 'Delete', wiki_path(wiki), method: :delete, class: "btn-sm btn-danger " %>
              <% if current_user.role == 'premium' %>
                <%= link_to "Collaborations", wiki_collaborations_path(wiki), class: "btn-sm btn-success"%>
              <% end %>
            </div>
          <% end %>
        </div>

        <div>
          <%= wiki.body.truncate(150) %>
        </div>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

app/views/welcome/about.html.erb
<h1>About Wikease</h1>

<p> Forged amidst the dying suns by Glen Cooney for <a href="https://www.bloc.io/web-development-bootcamp">Bloc's Fullstack Developer Bootcamp</a>.</p>

app/views/welcome/index.html.erb
<div id="welcome_text">
  <div class="welcome_message">Welcome to Wikease!</div>
  <div>The latest and greatest wiki for all things worth knowing. </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: 'Title for this Wiki', style: 'width:100%' %>
  </div>
  <div class="clearfix"> </div>

  <div class="field">
    <%= f.text_area :body, rows: 20, style: 'width:100%;', placeholder: 'Share your wisdom here' %>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>

  <% if current_user.role == 'premium' || current_user.role == 'admin' %>
    <div class="field", style="display:inline-block;">
      <%= f.label :private %> <%= f.check_box :private %>
    </div>
  <% end %>
<% end %>

app/views/wikis/_wikis.html.erb
<% @wikis.each do |wiki| %>
  <tr>
    <td><%= link_to wiki.title.truncate(50), wiki_path(wiki) %></td>
    <td> <%= link_to wiki.user.email, user_path(wiki.user) %></td>
  </tr>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr class="index-table-header-container">
      <td class="index-table-header"> Entry </td>
      <td class="index-table-header"> Author </td>
    </tr>
    <%= render 'wikis/wikis' %>
  </tbody>
</table>

app/views/wikis/new.html.erb
<h2>New Wiki</h2>

<%= render 'form' %>

app/views/wikis/show.html.erb
<% if(@wiki.user == current_user)  %>
  <div class="pull-right">
    <%= link_to 'Edit', edit_wiki_path(@wiki), class: "btn btn-info" %> <%= link_to 'Delete', wiki_path(@wiki), method: :delete, class: "btn btn-danger " %>
  </div>
<% end %>


<h2> <%= @wiki.title %> </h2>

<p>
  <%= markdown(@wiki.body) %>
</p>

<p>
  <strong>Author:</strong> <%= @wiki.user.email %>
</p>

<% if @wiki.collaborations.any? %>
  <strong>Contributors</strong>
  <p>
    <% if @wiki.users.any? %>
      <% @wiki.users.each do |u| %>
        <p> <%= u.email %> </p>
      <% end %>
    <% end %>
  </p>
<% end %>

<% if (current_user.role == 'premium' && @wiki.user == current_user) || current_user.role == 'admin' %>
  <%= link_to "Collaborations", wiki_collaborations_path(@wiki), class: "btn btn-success" %>
<% end %>